# Generated by Django 3.2.5 on 2021-07-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=60)),
                ('nivel_acceso', models.CharField(blank=True, max_length=30, null=True)),
                ('tpo_prsna', models.CharField(blank=True, max_length=10, null=True)),
                ('nm_prsna', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_prsna', models.CharField(blank=True, max_length=50, null=True)),
                ('nm_emprsa', models.CharField(blank=True, max_length=60, null=True)),
                ('cc_nit', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tlfno', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=17, null=True)),
                ('token_password', models.CharField(blank=True, max_length=100, null=True)),
                ('password_updated', models.BooleanField(blank=True, null=True)),
                ('date_password_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
